/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main() {
    int sum = 0, val_prev = 1, val_cur = 2;
    while (val_cur < 4000000) {
        /* add value to sum BEFORE incrementing value:
           this ensures we don't add a value greater than 4M to our sum */
        if (val_cur % 2 == 0) {
            sum += val_cur;
            printf("%d -> %d\n", val_cur, sum);
        } else {
            /* interestingly, the 2nd and 3rd values of each set of 3 are
               what get skipped */
            printf("%d -> skip\n", val_cur);
        }
        int val_next = val_prev + val_cur;
        val_prev = val_cur;
        val_cur = val_next;
    }
    printf("sum: %d\n", sum);
    return 0;
}
